/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSunglassesRouteImport } from './routes/services.sunglasses'
import { Route as ServicesPrivateEyeExamsRouteImport } from './routes/services.private-eye-exams'
import { Route as ServicesNhsEyeExamsRouteImport } from './routes/services.nhs-eye-exams'
import { Route as ServicesFramesAndLensesRouteImport } from './routes/services.frames-and-lenses'
import { Route as ServicesContactLensesRouteImport } from './routes/services.contact-lenses'
import { Route as ServicesChildrensEyecareRouteImport } from './routes/services.childrens-eyecare'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSunglassesRoute = ServicesSunglassesRouteImport.update({
  id: '/services/sunglasses',
  path: '/services/sunglasses',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrivateEyeExamsRoute = ServicesPrivateEyeExamsRouteImport.update({
  id: '/services/private-eye-exams',
  path: '/services/private-eye-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNhsEyeExamsRoute = ServicesNhsEyeExamsRouteImport.update({
  id: '/services/nhs-eye-exams',
  path: '/services/nhs-eye-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFramesAndLensesRoute = ServicesFramesAndLensesRouteImport.update({
  id: '/services/frames-and-lenses',
  path: '/services/frames-and-lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesContactLensesRoute = ServicesContactLensesRouteImport.update({
  id: '/services/contact-lenses',
  path: '/services/contact-lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesChildrensEyecareRoute =
  ServicesChildrensEyecareRouteImport.update({
    id: '/services/childrens-eyecare',
    path: '/services/childrens-eyecare',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/childrens-eyecare': typeof ServicesChildrensEyecareRoute
  '/services/contact-lenses': typeof ServicesContactLensesRoute
  '/services/frames-and-lenses': typeof ServicesFramesAndLensesRoute
  '/services/nhs-eye-exams': typeof ServicesNhsEyeExamsRoute
  '/services/private-eye-exams': typeof ServicesPrivateEyeExamsRoute
  '/services/sunglasses': typeof ServicesSunglassesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/childrens-eyecare': typeof ServicesChildrensEyecareRoute
  '/services/contact-lenses': typeof ServicesContactLensesRoute
  '/services/frames-and-lenses': typeof ServicesFramesAndLensesRoute
  '/services/nhs-eye-exams': typeof ServicesNhsEyeExamsRoute
  '/services/private-eye-exams': typeof ServicesPrivateEyeExamsRoute
  '/services/sunglasses': typeof ServicesSunglassesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/childrens-eyecare': typeof ServicesChildrensEyecareRoute
  '/services/contact-lenses': typeof ServicesContactLensesRoute
  '/services/frames-and-lenses': typeof ServicesFramesAndLensesRoute
  '/services/nhs-eye-exams': typeof ServicesNhsEyeExamsRoute
  '/services/private-eye-exams': typeof ServicesPrivateEyeExamsRoute
  '/services/sunglasses': typeof ServicesSunglassesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/reviews'
    | '/sitemap.xml'
    | '/services/childrens-eyecare'
    | '/services/contact-lenses'
    | '/services/frames-and-lenses'
    | '/services/nhs-eye-exams'
    | '/services/private-eye-exams'
    | '/services/sunglasses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/reviews'
    | '/sitemap.xml'
    | '/services/childrens-eyecare'
    | '/services/contact-lenses'
    | '/services/frames-and-lenses'
    | '/services/nhs-eye-exams'
    | '/services/private-eye-exams'
    | '/services/sunglasses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/reviews'
    | '/sitemap.xml'
    | '/services/childrens-eyecare'
    | '/services/contact-lenses'
    | '/services/frames-and-lenses'
    | '/services/nhs-eye-exams'
    | '/services/private-eye-exams'
    | '/services/sunglasses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesChildrensEyecareRoute: typeof ServicesChildrensEyecareRoute
  ServicesContactLensesRoute: typeof ServicesContactLensesRoute
  ServicesFramesAndLensesRoute: typeof ServicesFramesAndLensesRoute
  ServicesNhsEyeExamsRoute: typeof ServicesNhsEyeExamsRoute
  ServicesPrivateEyeExamsRoute: typeof ServicesPrivateEyeExamsRoute
  ServicesSunglassesRoute: typeof ServicesSunglassesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sunglasses': {
      id: '/services/sunglasses'
      path: '/services/sunglasses'
      fullPath: '/services/sunglasses'
      preLoaderRoute: typeof ServicesSunglassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/private-eye-exams': {
      id: '/services/private-eye-exams'
      path: '/services/private-eye-exams'
      fullPath: '/services/private-eye-exams'
      preLoaderRoute: typeof ServicesPrivateEyeExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/nhs-eye-exams': {
      id: '/services/nhs-eye-exams'
      path: '/services/nhs-eye-exams'
      fullPath: '/services/nhs-eye-exams'
      preLoaderRoute: typeof ServicesNhsEyeExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/frames-and-lenses': {
      id: '/services/frames-and-lenses'
      path: '/services/frames-and-lenses'
      fullPath: '/services/frames-and-lenses'
      preLoaderRoute: typeof ServicesFramesAndLensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/contact-lenses': {
      id: '/services/contact-lenses'
      path: '/services/contact-lenses'
      fullPath: '/services/contact-lenses'
      preLoaderRoute: typeof ServicesContactLensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/childrens-eyecare': {
      id: '/services/childrens-eyecare'
      path: '/services/childrens-eyecare'
      fullPath: '/services/childrens-eyecare'
      preLoaderRoute: typeof ServicesChildrensEyecareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesChildrensEyecareRoute: ServicesChildrensEyecareRoute,
  ServicesContactLensesRoute: ServicesContactLensesRoute,
  ServicesFramesAndLensesRoute: ServicesFramesAndLensesRoute,
  ServicesNhsEyeExamsRoute: ServicesNhsEyeExamsRoute,
  ServicesPrivateEyeExamsRoute: ServicesPrivateEyeExamsRoute,
  ServicesSunglassesRoute: ServicesSunglassesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
